# config.py — Blockly Switch Interface Configuration
# Generated by Blockly Shortcut Configurator
# 2026-05-07 08:50:27 UTC  |  OS: macOS
#
# Copy this file to your CircuitPython CIRCUITPY drive.
# It is imported by code.py to override the defaults.
#
# ─────────────────────────────────────────────────────
# USAGE IN code.py (place AFTER KEYCODES / KEY_SYMBOLS):
#   try:
#       from config import *
#   except ImportError:
#       pass   # use defaults if config.py is missing
# ─────────────────────────────────────────────────────

# ── SINGLE-SWITCH TIMING ─────────────────────────────

HOLD_TO_SCAN_SECS   = 2.0
SCAN_INTERVAL_SECS  = 1.0
MAX_SHORT_PRESS_SECS = 0.50

# ── TWO-SWITCH TIMING ────────────────────────────────

DEBOUNCE_TIME = 0.10

# ── KEYBOARD SHORTCUTS (macOS) ──────────────────
# Order = scan / navigation sequence.
# Multi-key combos: list modifiers first.
# e.g. ("cmd+z", [Keycode.LEFT_GUI, Keycode.Z])

from adafruit_hid.keycode import Keycode

KEYCODES = [
    ("tab",  [Keycode.TAB]),
    ("cmd+enter",  [Keycode.LEFT_GUI, Keycode.ENTER]),
    ("arrow right",  [Keycode.RIGHT_ARROW]),
    ("arrow down",  [Keycode.DOWN_ARROW]),
    ("enter",  [Keycode.ENTER]),
    ("arrow left",  [Keycode.LEFT_ARROW]),
    ("arrow up",  [Keycode.UP_ARROW]),
    ("delete",  [Keycode.DELETE]),
    ("w",  [Keycode.W]),
    ("t",  [Keycode.T]),
    ("cmd+o",  [Keycode.LEFT_GUI, Keycode.O]),
]

# ── TFT DISPLAY SYMBOLS ──────────────────────────────
# Shown on the 240×135 TFT. Keep to 1–3 characters.

KEY_SYMBOLS = {
    "tab": "tb",
    "cmd+enter": "ce",
    "arrow right": "R",
    "arrow down": "D",
    "enter": "e",
    "arrow left": "L",
    "arrow up": "U",
    "delete": "x",
    "w": "W",
    "t": "T",
    "cmd+o": "co",
}
